/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TaggingV3RouteImport } from './routes/tagging-v3'
import { Route as IndexRouteImport } from './routes/index'

const TaggingV3Route = TaggingV3RouteImport.update({
  id: '/tagging-v3',
  path: '/tagging-v3',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/tagging-v3': typeof TaggingV3Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tagging-v3': typeof TaggingV3Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/tagging-v3': typeof TaggingV3Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tagging-v3'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/tagging-v3'
  id: '__root__' | '/' | '/tagging-v3'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TaggingV3Route: typeof TaggingV3Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tagging-v3': {
      id: '/tagging-v3'
      path: '/tagging-v3'
      fullPath: '/tagging-v3'
      preLoaderRoute: typeof TaggingV3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TaggingV3Route: TaggingV3Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
