/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TagReportRouteImport } from './routes/tag-report'
import { Route as LabelingReportRouteImport } from './routes/labeling-report'
import { Route as IndexRouteImport } from './routes/index'

const TagReportRoute = TagReportRouteImport.update({
  id: '/tag-report',
  path: '/tag-report',
  getParentRoute: () => rootRouteImport,
} as any)
const LabelingReportRoute = LabelingReportRouteImport.update({
  id: '/labeling-report',
  path: '/labeling-report',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/labeling-report': typeof LabelingReportRoute
  '/tag-report': typeof TagReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/labeling-report': typeof LabelingReportRoute
  '/tag-report': typeof TagReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/labeling-report': typeof LabelingReportRoute
  '/tag-report': typeof TagReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/labeling-report' | '/tag-report'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/labeling-report' | '/tag-report'
  id: '__root__' | '/' | '/labeling-report' | '/tag-report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LabelingReportRoute: typeof LabelingReportRoute
  TagReportRoute: typeof TagReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tag-report': {
      id: '/tag-report'
      path: '/tag-report'
      fullPath: '/tag-report'
      preLoaderRoute: typeof TagReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labeling-report': {
      id: '/labeling-report'
      path: '/labeling-report'
      fullPath: '/labeling-report'
      preLoaderRoute: typeof LabelingReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LabelingReportRoute: LabelingReportRoute,
  TagReportRoute: TagReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
